// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Persistence.Db;

#nullable disable

namespace User.Persistence.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("FeaturePermission", b =>
                {
                    b.Property<int>("FeaturesFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionsPermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeaturesFeatureId", "PermissionsPermissionId");

                    b.HasIndex("PermissionsPermissionId");

                    b.ToTable("FeaturePermission");

                    b.HasData(
                        new
                        {
                            FeaturesFeatureId = 1,
                            PermissionsPermissionId = 1
                        },
                        new
                        {
                            FeaturesFeatureId = 1,
                            PermissionsPermissionId = 2
                        },
                        new
                        {
                            FeaturesFeatureId = 1,
                            PermissionsPermissionId = 3
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 4
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 5
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 6
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 7
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 8
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            PermissionsPermissionId = 9
                        },
                        new
                        {
                            FeaturesFeatureId = 3,
                            PermissionsPermissionId = 10
                        },
                        new
                        {
                            FeaturesFeatureId = 3,
                            PermissionsPermissionId = 11
                        },
                        new
                        {
                            FeaturesFeatureId = 3,
                            PermissionsPermissionId = 12
                        },
                        new
                        {
                            FeaturesFeatureId = 4,
                            PermissionsPermissionId = 13
                        });
                });

            modelBuilder.Entity("FeatureRole", b =>
                {
                    b.Property<int>("FeaturesFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolesRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeaturesFeatureId", "RolesRoleId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("FeatureRole");

                    b.HasData(
                        new
                        {
                            FeaturesFeatureId = 1,
                            RolesRoleId = 1
                        },
                        new
                        {
                            FeaturesFeatureId = 2,
                            RolesRoleId = 1
                        },
                        new
                        {
                            FeaturesFeatureId = 3,
                            RolesRoleId = 1
                        },
                        new
                        {
                            FeaturesFeatureId = 4,
                            RolesRoleId = 1
                        },
                        new
                        {
                            FeaturesFeatureId = 1,
                            RolesRoleId = 2
                        },
                        new
                        {
                            FeaturesFeatureId = 3,
                            RolesRoleId = 2
                        },
                        new
                        {
                            FeaturesFeatureId = 4,
                            RolesRoleId = 2
                        });
                });

            modelBuilder.Entity("FeatureUserK", b =>
                {
                    b.Property<int>("BetaFeaturesFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersUserKId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BetaFeaturesFeatureId", "UsersUserKId");

                    b.HasIndex("UsersUserKId");

                    b.ToTable("BetaFeatureUserK", (string)null);
                });

            modelBuilder.Entity("User.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Beta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Beta = false,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7257),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7259),
                            ModifiedBy = "DbInit",
                            Name = "client"
                        },
                        new
                        {
                            FeatureId = 2,
                            Beta = false,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7260),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7261),
                            ModifiedBy = "DbInit",
                            Name = "user"
                        },
                        new
                        {
                            FeatureId = 3,
                            Beta = false,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7263),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7264),
                            ModifiedBy = "DbInit",
                            Name = "task"
                        },
                        new
                        {
                            FeatureId = 4,
                            Beta = false,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7265),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7266),
                            ModifiedBy = "DbInit",
                            Name = "contract"
                        });
                });

            modelBuilder.Entity("User.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7310),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7312),
                            ModifiedBy = "DbInit",
                            Name = "client.read"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7313),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7314),
                            ModifiedBy = "DbInit",
                            Name = "client.create"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7315),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7316),
                            ModifiedBy = "DbInit",
                            Name = "client.update"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7317),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7318),
                            ModifiedBy = "DbInit",
                            Name = "user.read"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7319),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7320),
                            ModifiedBy = "DbInit",
                            Name = "user.impersonate"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7321),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7322),
                            ModifiedBy = "DbInit",
                            Name = "user.create"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7324),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7325),
                            ModifiedBy = "DbInit",
                            Name = "user.update"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7326),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7327),
                            ModifiedBy = "DbInit",
                            Name = "user.suspend"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7328),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7329),
                            ModifiedBy = "DbInit",
                            Name = "user.deactivate"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7330),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7331),
                            ModifiedBy = "DbInit",
                            Name = "task.read"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7332),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7333),
                            ModifiedBy = "DbInit",
                            Name = "task.create"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7334),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7335),
                            ModifiedBy = "DbInit",
                            Name = "task.update"
                        },
                        new
                        {
                            PermissionId = 13,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7336),
                            CreatedBy = "DbInit",
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7337),
                            ModifiedBy = "DbInit",
                            Name = "contract.read"
                        });
                });

            modelBuilder.Entity("User.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fonction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7123),
                            CreatedBy = "DbInit",
                            Fonction = 5,
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7168),
                            ModifiedBy = "DbInit",
                            Name = "Entreprise | Support",
                            UserType = 0
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7170),
                            CreatedBy = "DbInit",
                            Fonction = 5,
                            ModifiedAt = new DateTime(2023, 4, 10, 19, 21, 25, 749, DateTimeKind.Local).AddTicks(7171),
                            ModifiedBy = "DbInit",
                            Name = "Entreprise | Distributeur",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("User.Domain.Entities.UserK", b =>
                {
                    b.Property<int>("UserKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserKId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FeaturePermission", b =>
                {
                    b.HasOne("User.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureRole", b =>
                {
                    b.HasOne("User.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureUserK", b =>
                {
                    b.HasOne("User.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("BetaFeaturesFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User.Domain.Entities.UserK", null)
                        .WithMany()
                        .HasForeignKey("UsersUserKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User.Domain.Entities.UserK", b =>
                {
                    b.HasOne("User.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("User.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
